package com.craftsentient.craftmind.activationFunctions;

public enum DEFAULT_ACTIVATION_FUNCTIONS {
    EXPONENTIAL_ELU_ACTIVATION_FUNCTION,
    GAUSSIAN_ACTIVATION_FUNCTION,
    LEAKY_RELU_ACTIVATION_FUNCTION,
    LINEAR_ACTIVATION_FUNCTION,
    MISH_ACTIVATION_FUNCTION,
    PARAMETRIC_RELU_ACTIVATION_FUNCTION,
    RELU_ACTIVATION_FUNCTION,
    SIGMOID_ACTIVATION_FUNCTION,
    SOFTMAX_ACTIVATION_FUNCTION,
    SOFTPLUS_ACTIVATION_FUNCTION,
    SWISH_ACTIVATION_FUNCTION,
    TANH_ACTIVATION_FUNCTION,
}
