package com.craftsentient.craftmind.errorLoss;

public enum DEFAULT_LOSSES {
    BINARY_CROSS_ENTROPY_LOSS_FUNCTION,
    CATEGORICAL_CROSS_ENTROPY_LOSS_FUNCTION,
    CONTRASTIVE_LOSS_FUNCTION,
    COSINE_PROXIMITY_LOSS_FUNCTION,
    FOCAL_LOSS_FUNCTION,
    HINGE_LOSS_FUNCTION,
    HUBER_LOSS_FUNCTION,
    KL_DIVERGENCE_LOSS_FUNCTION,
    LOG_COSH_LOSS_FUNCTION,
    L1_LOSS_FUNCTION,
    MAPE_LOSS_FUNCTION,
    MSE_LOSS_FUNCTION,
    MSLE_LOSS_FUNCTION,
    NLL_LOSS_FUNCTION,
    QUADRATIC_LOSS,
    RANKNET_LOSS_FUNCTION,
    SPARSE_CATEGORICAL_CROSS_ENTROPY_LOSS_FUNCTION,
    SQUARED_HINGE_LOSS_FUNCTION,
    SSIM_LOSS_FUNCTION,
    TRIPLET_MARGIN_LOSS_FUNCTION
}
